version: '2'
services:

  core:
    restart: always
    container_name: dmoney-core
    build: docker/core
    env_file:
      - .env
      - .env-seed
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      PGHOST: postgres

  horizon:
    restart: always
    container_name: dmoney-horizon
    build: docker/horizon
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/horizon?sslmode=disable"
      STELLAR_CORE_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/stellar?sslmode=disable"
      BANK_MASTER_KEY: ${BANK_MASTER_KEY}
      BANK_COMMISSION_KEY: ${BANK_COMMISSION_KEY}
      NETWORK_PASSPHRASE: ${NETWORK_PASSPHRASE}
      STELLAR_CORE_URL: "http://core:11626"
      REDIS_URL: "redis://redis:6379"
      LOG_LEVEL: "info"
      INGEST: "true"

  postgres:
    restart: always
    container_name: dmoney-postgres
    build: docker/postgres
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"

  redis:
    restart: always
    container_name: dmoney-redis
    image: redis:3.2